export const FACULTY_LOGIN_REQUEST = "FACULTY_LOGIN_REQUEST";
export const FACULTY_LOGIN_SUCCESS = "FACULTY_LOGIN_SUCCESS";
export const FACULTY_LOGIN_FAIL = "FACULTY_LOGIN_FAIL";
export const FACULTY_LOGOUT = "FACULTY_LOGOUT";