export const FACULTY_LOGIN_REQUEST = "FACULTY_LOGIN_REQUEST";
export const FACULTY_LOGIN_SUCCESS = "FACULTY_LOGIN_SUCCESS";
export const FACULTY_LOGIN_FAIL = "FACULTY_LOGIN_FAIL";
export const FACULTY_LOGOUT = "FACULTY_LOGOUT";

export const FACULTY_REGISTER_REQUEST = "FACULTY_REGISTER_PANEL_REQUEST";
export const FACULTY_REGISTER_SUCCESS = "FACULTY_REGISTER_PANEL_SUCCESS";
export const FACULTY_REGISTER_FAIL = "FACULTY_REGISTER_PANEL_FAIL";

export const FACULTY_SUPERVISOR_LIST_REQUEST = "FACULTY_SUPERVISOR_LIST_REQUEST";
export const FACULTY_SUPERVISOR_LIST_SUCCESS = "FACULTY_SUPERVISOR_LIST_SUCCESS";
export const FACULTY_SUPERVISOR_LIST_FAIL = "FACULTY_SUPERVISOR_LIST_FAIL";

export const FACULTY_UPDATE_NO_SUPERVISION_REQUEST = "FACULTY_UPDATE_NO_SUPERVISION_REQUEST";
export const FACULTY_UPDATE_NO_SUPERVISION_SUCCESS = "FACULTY_UPDATE_NO_SUPERVISION_SUCCESS";
export const FACULTY_UPDATE_NO_SUPERVISION_FAIL = "FACULTY_UPDATE_NO_SUPERVISION_FAIL";

export const FACULTY_APPLICATION_LIST_REQUEST = "FACULTY_RPD_APPLICATION_LIST_REQUEST";
export const FACULTY_APPLICATION_LIST_SUCCESS = "FACULTY_RPD_APPLICATION_LIST_SUCCESS ";
export const FACULTY_APPLICATION_LIST_FAIL = "FACULTY_RPD_APPLICATION_LIST_FAIL";
