export const PANEL_LOGIN_REQUEST = "PANEL_LOGIN_REQUEST";
export const PANEL_LOGIN_SUCCESS = "PANEL_LOGIN_SUCCESS";
export const PANEL_LOGIN_FAIL = "PANEL_LOGIN_FAIL";
export const PANEL_LOGOUT = "PANEL_LOGOUT";

export const PANEL_RPD_LIST_REQUEST = "PANEL_RPD_LIST_REQUEST";
export const PANEL_RPD_LIST_SUCCESS = "PANEL_RPD_LIST_SUCCESS";
export const PANEL_RPD_LIST_FAIL = "PANEL_RPD_LIST_FAIL";

export const PANEL_UPDATE_APPLICATION_REQUEST = "PANEL_UPDATE_APPLICATION_REQUEST";
export const PANEL_REJECT_APPLICATION_SUCCESS = "PANEL_REJECT_APPLICATION_SUCCESS";
export const PANEL_APPROVE_APPLICATION_SUCCESS = "PANEL_APPROVE_APPLICATION_SUCCESS";
export const PANEL_UPDATE_APPLICATION_FAIL = "PANEL_UPDATE_APPLICATION_FAIL";