export const PANEL_LOGIN_REQUEST = "PANEL_LOGIN_REQUEST";
export const PANEL_LOGIN_SUCCESS = "PANEL_LOGIN_SUCCESS";
export const PANEL_LOGIN_FAIL = "PANEL_LOGIN_FAIL";
export const PANEL_LOGOUT = "PANEL_LOGOUT";