export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";

export const STUDENT_CW_READ_REQUEST = "STUDENT_CW_READ_REQUEST";
export const STUDENT_CW_READ_SUCCESS = "STUDENT_CW_READ_SUCCESS";
export const STUDENT_CW_READ_FAIL = "STUDENT_CW_READ_FAIL"

export const STUDENT_CW_REQUEST = "STUDENT_CW_REQUEST";
export const STUDENT_CW_SUCCESS = "STUDENT_CW_SUCCESS";
export const STUDENT_CW_FAIL = "STUDENT_CW_FAIL";

export const STUDENT_APPLICATION = "STUDENT_APPLICATION";
export const STUDENT_APPLICATION_2 = "STUDENT_APPLICATION_2";
export const STUDENT_MEETING_LOG = "STUDENT_MEETING_LOG";