export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";

export const STUDENT_RPD_REQUEST = "STUDENT_RPD_REQUEST";
export const STUDENT_RPD_SUCCESS = "STUDENT_RPD_SUCCESS";
export const STUDENT_RPD_FAIL = "STUDENT_RPD_FAIL";

export const STUDENT_APPLICATION = "STUDENT_APPLICATION";
// export const STUDENT_APPLICATION_REJECT = "STUDENT_APPLICATION_REJECT";