export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";