export const SUPERVISOR_LOGIN_REQUEST = "SUPERVISOR_LOGIN_REQUEST";
export const SUPERVISOR_LOGIN_SUCCESS = "SUPERVISOR_LOGIN_SUCCESS";
export const SUPERVISOR_LOGIN_FAIL = "SUPERVISOR_LOGIN_FAIL";
export const SUPERVISOR_LOGOUT = "SUPERVISOR_LOGOUT";

export const SUPERVISOR_STUDENT_LIST_REQUEST = "SUPERVISOR_STUDENT_LIST_REQUEST";
export const SUPERVISOR_STUDENT_LIST_SUCCESS = "SUPERVISOR_STUDENT_LIST_SUCCESS";
export const SUPERVISOR_STUDENT_LIST_FAIL = "SUPERVISOR_STUDENT_LIST_FAIL";

export const SUPERVISOR_CHOOSE_STUDENT_REQUEST = "SUPERVISOR_CHOOSE_STUDENT_REQUEST";
export const SUPERVISOR_CHOOSE_STUDENT_SUCCESS = "SUPERVISOR_CHOOSE_STUDENT_SUCCESS";
export const SUPERVISOR_CHOOSE_STUDENT_FAIL = "SUPERVISOR_CHOOSE_STUDENT_FAIL";