export const SUPERVISOR_LOGIN_REQUEST = "SUPERVISOR_LOGIN_REQUEST";
export const SUPERVISOR_LOGIN_SUCCESS = "SUPERVISOR_LOGIN_SUCCESS";
export const SUPERVISOR_LOGIN_FAIL = "SUPERVISOR_LOGIN_FAIL";
export const SUPERVISOR_LOGOUT = "SUPERVISOR_LOGOUT";
