export const SUPERVISOR_LOGIN_REQUEST = "SUPERVISOR_LOGIN_REQUEST";
export const SUPERVISOR_LOGIN_SUCCESS = "SUPERVISOR_LOGIN_SUCCESS";
export const SUPERVISOR_LOGIN_FAIL = "SUPERVISOR_LOGIN_FAIL";
export const SUPERVISOR_LOGOUT = "SUPERVISOR_LOGOUT";

export const SUPERVISOR_MEETING_LOG_REQUEST = "SUPERVISOR_MEETING_LOG_REQUEST";
export const SUPERVISOR_MEETING_LOG_SUCCESS = "SUPERVISOR_MEETING_LOG_SUCCESS";
export const SUPERVISOR_MEETING_LOG_FAIL = "SUPERVISOR_MEETING_LOG_FAIL";