// Production Build Testing (replace it with the https url that is generated by ngrok *(use the https tunnel))
// export const BASE_URL = 'https://c0b5-2001-d08-c2-cc4-a4e3-7e8f-1522-ba3a.ngrok-free.app/'

export const BASE_URL = 'http://localhost:5000/'
export const BASE_URL_2 = 'http://localhost:5000/'